#! /bin/sh

bspc config border_width        2
bspc config window_gap          9

bspc config top_padding 15
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer   true
bspc config auto_alternate          true
bspc config active_border_color "#504339"
bspc config focused_border_color "#817267"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#504339"
bspc config focused_locked_border_color "#8c644c"

bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

bspc monitor -d 000 001 010 011 100 101 110 111 X

bspc rule -a xchat floating=on 
bspc rule -a mpv floating=on

nitrogen --restore &
nm-applet &
caffeine &
volumeicon &
tint2 &
